In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

In [2]:
df = pd.read_csv("IMDb_TOP50_Reviews.csv")
df.head()

,Movie,Review Text,IMDb Rating
0,The Shawshank Redemption,A profound masterpiece about the resilience of...,10
1,The Godfather,The pinnacle of crime drama. Coppola's directi...,10
2,The Dark Knight,Nolan redefined the superhero genre. Ledger’s ...,9
3,Breaking Bad,The greatest character study ever televised. W...,10
4,The Sopranos,Revolutionized television. James Gandolfini’s ...,10

In [3]:
import re
import nltk
from nltk.corpus import stopwords
stopwords_list = set(stopwords.words('english'))


TAG_RE = re.compile(r'<[^>]+>')

def remove_tags(text):
    return TAG_RE.sub('', text)
    

class CustomPreprocess():

    def __init__(self):
        pass

    def preprocess_text(self,sen):
        sen = sen.lower()
        
        # Remove html tags
        sentence = remove_tags(sen)

        # Remove punctuations and numbers
        sentence = re.sub('[^a-zA-Z]', ' ', sentence)
        
        # Single character removal
        sentence = re.sub(r"\s+[a-zA-Z]\s+", ' ', sentence)

        # Remove multiple spaces
        sentence = re.sub(r'\s+', ' ', sentence)
        
        # Remove Stopwords
        pattern = re.compile(r'\b(' + r'|'.join(stopwords_list) + r')\b\s*')
        sentence = pattern.sub('', sentence)
        
        return sentence

In [4]:
custom = CustomPreprocess()
unseen_reviews = df['Review Text']

unseen_processed = []
for review in unseen_reviews:
    review = custom.preprocess_text(review)
    unseen_processed.append(review)

In [5]:
unseen_processed[:3]

['profound masterpiece resilience human spirit chemistry robbins freeman legendary ending perhaps satisfying cinematic history ',
 'pinnacle crime drama coppola direction brando performance create haunting beautiful portrait power family never surpassed ',
 'nolan redefined superhero genre ledger joker chaotic force nature makes high stakes crime thriller comic book movie ']

In [6]:
# Loading
import io
import json
from tensorflow.keras.preprocessing.text import tokenizer_from_json, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import load_model

with open('tokenizer.json') as f:
    data = json.load(f)
    loaded_tokenizer = tokenizer_from_json(data)

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(unseen_processed)
# unseen_tokenized  = tokenizer.texts_to_sequences(unseen_processed)
unseen_tokenized = loaded_tokenizer.texts_to_sequences(unseen_processed)

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
unseen_padded = pad_sequences(unseen_tokenized, padding='post', maxlen=100)

In [9]:
unseen_padded[:2]

array([[ 3123,   770, 27210,   271,   986,  1080,  4878,  3023,  2452,
          154,   262,  2209,  1157,   352,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [11273,   640,   323,  5820,   331,  3491,   129,   848,  2204,
          197,  3063,   511,   118,    34,  9246,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0]], dtype=int32)

In [10]:
model = load_model("sentiment_classifier2.h5")

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [11]:
try:
    pred = model.predict(unseen_padded, batch_size=len(unseen_padded))
except ValueError:
    # If that fails, the model might only want 1 review at a time
    print("🔄 Standard prediction failed, trying manual loop...")
    pred = []
    for review in unseen_padded:
        # Reshape to (1, 100) because the model expects [Batch_Size, Max_Length]
        single_pred = model.predict(review.reshape(1, 100), verbose=0)
        pred.append(single_pred[0])
    pred = np.array(pred)

print("✅ Prediction complete!")
print(pred[:5]) # Show first 5 results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step
✅ Prediction complete!
[[0.98957974]
 [0.9883966 ]
 [0.9839054 ]
 [0.9892361 ]
 [0.9885676 ]]

In [17]:
pred_df = df.drop(columns=["Unnamed: 0"], errors="ignore")
pred_df

,Movie,Review Text,IMDb Rating
0,The Shawshank Redemption,A profound masterpiece about the resilience of...,10
1,The Godfather,The pinnacle of crime drama. Coppola's directi...,10
2,The Dark Knight,Nolan redefined the superhero genre. Ledger’s ...,9
3,Breaking Bad,The greatest character study ever televised. W...,10
4,The Sopranos,Revolutionized television. James Gandolfini’s ...,10
5,Band of Brothers,"A visceral, deeply moving tribute to the men w...",10
6,Chernobyl,"A chilling, claustrophobic look at human error...",9
7,Avatar: The Last Airbender,Perfect storytelling for all ages. It balances...,10
8,The Wire,"A gritty, uncompromising look at the American ...",9
9,Game of Thrones,"Despite a divisive ending, the first six seaso...",8
10,Interstellar,Visually stunning and emotionally heavy. Nolan...,9
11,Pulp Fiction,Tarantino’s dialogue is electric. The non-line...,9
12,Schindler's List,A heartbreaking but essential film. Spielberg ...,10
13,Parasite,A genre-bending social satire that keeps you g...,10
14,The Lord of the Rings: Return of the King,The gold standard for fantasy epics. The scale...,10
15,Succession,"A biting, hilarious, and often painful look at...",9
16,Better Call Saul,A rare prequel that rivals the original. Jimmy...,9
17,Arcane,"Breathtaking animation meets a mature, tragic ...",10
18,The Last of Us,The best video game adaptation ever made. It p...,9
19,Stranger Things,A perfect blend of 80s nostalgia and modern ho...,8
20,Ex Machina,Overrated and pretentious. It tries to be deep...,3
21,Eternals,The worst MCU film by a mile. The characters a...,2
22,Joker (2019),"A miserable, hollow experience. It mimics bett...",4
23,The Batman (2022),Far too long and incredibly gloomy. Pattinson ...,5
24,Star Wars: The Rise of Skywalker,A complete disaster that ruins years of world-...,1
25,Velma,Absolutely unwatchable. It insults the origina...,1
26,The Idol,"A pretentious, voyeuristic mess. The acting is...",1
27,She-Hulk,The writing is cringeworthy and the CGI is unf...,2
28,Secret Invasion,A massive disappointment for Marvel fans. It t...,3
29,The Rings of Power,"Beautiful to look at, but empty inside. The pa...",4
30,Inception,Way too complicated for its own good. It spend...,5
31,The Big Bang Theory,Lazy writing and canned laughter. It relies on...,2
32,Grey's Anatomy,Should have ended ten years ago. It’s now just...,4
33,Iron Man 3,The twist with the Mandarin was a slap in the ...,3
34,Thor: Love and Thunder,Too much screaming goats and forced jokes. It ...,3
35,Emily in Paris,"A shallow, stereotypical nightmare. The main c...",2
36,True Detective (Season 2),A confusing mess after a perfect first season....,4
37,Lost (The Finale),One of the biggest letdowns in TV history. Aft...,2
38,Man of Steel,Too much CGI destruction and not enough hope. ...,4
39,Quantum of Solace,"A dull, edited-to-death Bond film. You can’t t...",3

In [18]:
pred_df["Predicted Sentiment"] = np.round(pred*10,1)
pred_df

,Movie,Review Text,IMDb Rating,Predicted Sentiment
0,The Shawshank Redemption,A profound masterpiece about the resilience of...,10,9.9
1,The Godfather,The pinnacle of crime drama. Coppola's directi...,10,9.9
2,The Dark Knight,Nolan redefined the superhero genre. Ledger’s ...,9,9.8
3,Breaking Bad,The greatest character study ever televised. W...,10,9.9
4,The Sopranos,Revolutionized television. James Gandolfini’s ...,10,9.9
5,Band of Brothers,"A visceral, deeply moving tribute to the men w...",10,9.9
6,Chernobyl,"A chilling, claustrophobic look at human error...",9,9.9
7,Avatar: The Last Airbender,Perfect storytelling for all ages. It balances...,10,9.9
8,The Wire,"A gritty, uncompromising look at the American ...",9,9.9
9,Game of Thrones,"Despite a divisive ending, the first six seaso...",8,9.9
10,Interstellar,Visually stunning and emotionally heavy. Nolan...,9,9.9
11,Pulp Fiction,Tarantino’s dialogue is electric. The non-line...,9,9.9
12,Schindler's List,A heartbreaking but essential film. Spielberg ...,10,9.9
13,Parasite,A genre-bending social satire that keeps you g...,10,9.9
14,The Lord of the Rings: Return of the King,The gold standard for fantasy epics. The scale...,10,9.9
15,Succession,"A biting, hilarious, and often painful look at...",9,9.8
16,Better Call Saul,A rare prequel that rivals the original. Jimmy...,9,9.9
17,Arcane,"Breathtaking animation meets a mature, tragic ...",10,9.9
18,The Last of Us,The best video game adaptation ever made. It p...,9,9.9
19,Stranger Things,A perfect blend of 80s nostalgia and modern ho...,8,9.9
20,Ex Machina,Overrated and pretentious. It tries to be deep...,3,0.0
21,Eternals,The worst MCU film by a mile. The characters a...,2,0.0
22,Joker (2019),"A miserable, hollow experience. It mimics bett...",4,0.0
23,The Batman (2022),Far too long and incredibly gloomy. Pattinson ...,5,0.3
24,Star Wars: The Rise of Skywalker,A complete disaster that ruins years of world-...,1,0.1
25,Velma,Absolutely unwatchable. It insults the origina...,1,0.0
26,The Idol,"A pretentious, voyeuristic mess. The acting is...",1,0.0
27,She-Hulk,The writing is cringeworthy and the CGI is unf...,2,0.1
28,Secret Invasion,A massive disappointment for Marvel fans. It t...,3,0.1
29,The Rings of Power,"Beautiful to look at, but empty inside. The pa...",4,0.0
30,Inception,Way too complicated for its own good. It spend...,5,9.6
31,The Big Bang Theory,Lazy writing and canned laughter. It relies on...,2,0.0
32,Grey's Anatomy,Should have ended ten years ago. It’s now just...,4,9.8
33,Iron Man 3,The twist with the Mandarin was a slap in the ...,3,7.7
34,Thor: Love and Thunder,Too much screaming goats and forced jokes. It ...,3,3.4
35,Emily in Paris,"A shallow, stereotypical nightmare. The main c...",2,0.0
36,True Detective (Season 2),A confusing mess after a perfect first season....,4,0.1
37,Lost (The Finale),One of the biggest letdowns in TV history. Aft...,2,9.8
38,Man of Steel,Too much CGI destruction and not enough hope. ...,4,3.5
39,Quantum of Solace,"A dull, edited-to-death Bond film. You can’t t...",3,0.0

In [15]:
pred_label = []
for i in list(pred_df["Predicted Sentiment"]):
    if i <= 5:
        pred_label.append("Negative")
    
    else:
        pred_label.append("Positive")

In [16]:
pred_df["Predicted Review Sentiment"] = pred_label
pred_df

,Movie,Review Text,IMDb Rating,Predicted Sentiment,Predicted Review Sentiment
0,The Shawshank Redemption,A profound masterpiece about the resilience of...,10,9.9,Positive
1,The Godfather,The pinnacle of crime drama. Coppola's directi...,10,9.9,Positive
2,The Dark Knight,Nolan redefined the superhero genre. Ledger’s ...,9,9.8,Positive
3,Breaking Bad,The greatest character study ever televised. W...,10,9.9,Positive
4,The Sopranos,Revolutionized television. James Gandolfini’s ...,10,9.9,Positive
5,Band of Brothers,"A visceral, deeply moving tribute to the men w...",10,9.9,Positive
6,Chernobyl,"A chilling, claustrophobic look at human error...",9,9.9,Positive
7,Avatar: The Last Airbender,Perfect storytelling for all ages. It balances...,10,9.9,Positive
8,The Wire,"A gritty, uncompromising look at the American ...",9,9.9,Positive
9,Game of Thrones,"Despite a divisive ending, the first six seaso...",8,9.9,Positive
10,Interstellar,Visually stunning and emotionally heavy. Nolan...,9,9.9,Positive
11,Pulp Fiction,Tarantino’s dialogue is electric. The non-line...,9,9.9,Positive
12,Schindler's List,A heartbreaking but essential film. Spielberg ...,10,9.9,Positive
13,Parasite,A genre-bending social satire that keeps you g...,10,9.9,Positive
14,The Lord of the Rings: Return of the King,The gold standard for fantasy epics. The scale...,10,9.9,Positive
15,Succession,"A biting, hilarious, and often painful look at...",9,9.8,Positive
16,Better Call Saul,A rare prequel that rivals the original. Jimmy...,9,9.9,Positive
17,Arcane,"Breathtaking animation meets a mature, tragic ...",10,9.9,Positive
18,The Last of Us,The best video game adaptation ever made. It p...,9,9.9,Positive
19,Stranger Things,A perfect blend of 80s nostalgia and modern ho...,8,9.9,Positive
20,Ex Machina,Overrated and pretentious. It tries to be deep...,3,0.0,Negative
21,Eternals,The worst MCU film by a mile. The characters a...,2,0.0,Negative
22,Joker (2019),"A miserable, hollow experience. It mimics bett...",4,0.0,Negative
23,The Batman (2022),Far too long and incredibly gloomy. Pattinson ...,5,0.3,Negative
24,Star Wars: The Rise of Skywalker,A complete disaster that ruins years of world-...,1,0.1,Negative
25,Velma,Absolutely unwatchable. It insults the origina...,1,0.0,Negative
26,The Idol,"A pretentious, voyeuristic mess. The acting is...",1,0.0,Negative
27,She-Hulk,The writing is cringeworthy and the CGI is unf...,2,0.1,Negative
28,Secret Invasion,A massive disappointment for Marvel fans. It t...,3,0.1,Negative
29,The Rings of Power,"Beautiful to look at, but empty inside. The pa...",4,0.0,Negative
30,Inception,Way too complicated for its own good. It spend...,5,9.6,Positive
31,The Big Bang Theory,Lazy writing and canned laughter. It relies on...,2,0.0,Negative
32,Grey's Anatomy,Should have ended ten years ago. It’s now just...,4,9.8,Positive
33,Iron Man 3,The twist with the Mandarin was a slap in the ...,3,7.7,Positive
34,Thor: Love and Thunder,Too much screaming goats and forced jokes. It ...,3,3.4,Negative
35,Emily in Paris,"A shallow, stereotypical nightmare. The main c...",2,0.0,Negative
36,True Detective (Season 2),A confusing mess after a perfect first season....,4,0.1,Negative
37,Lost (The Finale),One of the biggest letdowns in TV history. Aft...,2,9.8,Positive
38,Man of Steel,Too much CGI destruction and not enough hope. ...,4,3.5,Negative
39,Quantum of Solace,"A dull, edited-to-death Bond film. You can’t t...",3,0.0,Negative